---
title: "Workingdoccasetsuyd2"
format: html
editor: visual
---

```{r setup}
#| include: false
# Load necessary packages
library(tidyverse)
library(tidymodels)
library(dplyr)
library(ggformula)
library(ggplot2) 
library(GGally)
##install.packages("vip")
library(mosaic)
library(ranger)
library(vip)
library(caret)
tidymodels_prefer(quiet = TRUE) 
```

```{r}
df <- read.csv('conversion_predictors_of_clinically_isolated_syndrome_to_multiple_sclerosis.csv')

df

##Group is repsonse, 1 is diagnosed, 0 is not diagnsoed
```

EDA
```{r}

summary(df)

missing_values <- sapply(df, function(x) mosaic::sum(is.na(x)))
missing_values
```
Missing values for Final_EDSS and Initial_EDSS (look into why)
```{r}

numeric_vars <- df |> 
  select_if(is.numeric)

numeric_vars 


numeric_vars_long <- numeric_vars |> 
  pivot_longer(cols = everything(), names_to = "variable", values_to = "value")

ggplot(numeric_vars_long, aes(x = value)) +
  geom_histogram(fill = "steelblue", color = "black", bins = 30) +
  facet_wrap(~variable, scales = "free") +
  theme_minimal() +
  labs(title = "Distribution of Numeric Variables")


cor_matrix <- mosaic::cor(numeric_vars, use = "complete.obs")
print(cor_matrix)

ggcorr(numeric_vars, label = TRUE, label_round = 2, label_size = 3, hjust = 0.75, size = 3) +
  theme_minimal() +
  labs(title = "Correlation Matrix of Numeric Variables")
```

